// ── CAREER JOURNEY: the career path, told team by team ──
//
// Everything comes from data/careers.json, generated by scripts/build-careers.js from
// the season files. No hardcoded prose: the milestones (debut, first points,
// first podium, first win, first pole, titles) are derived from real
// results, so the section builds itself for any driver in the dataset.
//
// Two pieces: a strip with one cell per year painted in the team color
// (the whole career at a glance), and a chapter per team with its identity
// block, its figures and the milestones as a grid of cards.

(function(){
    const TWEMOJI_BASE = 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/';

    const root = document.getElementById('driverBio');
    if(!root) return;

    const driverId = new URLSearchParams(location.search).get('driver') || 'max-verstappen';

    const flagUrl = iso => {
        if(!iso || iso.length !== 2) return null;
        const code = [...iso.toUpperCase()]
            .map(c => (0x1F1E6 + c.charCodeAt(0) - 65).toString(16))
            .join('-');
        return `${TWEMOJI_BASE}${code}.svg`;
    };

    const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    const prettyDate = iso => {
        const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso || '');
        return m ? `${Number(m[3])} ${MONTHS[Number(m[2]) - 1]} ${m[1]}` : '';
    };

    // "2015, 2016" → "2015–2016";  "2016, 2017, 2026" → "2016–2017 · 2026"
    // A continuous range would be lying if there are seasons not raced in between.
    function seasonLabel(seasons){
        const runs = [];
        for(const y of seasons){
            const last = runs[runs.length - 1];
            if(last && y === last[last.length - 1] + 1) last.push(y);
            else runs.push([y]);
        }
        return runs
            .map(r => r.length === 1 ? `${r[0]}` : `${r[0]}–${r[r.length - 1]}`)
            .join(' · ');
    }

    const plural = (n, word) => `${n} ${word}${n === 1 ? '' : 's'}`;
    const fmtNum = n => Number(n).toLocaleString('en-US');
    const pad2 = n => String(n).padStart(2, '0');

    // Several milestones can land on the same race (winning on your first podium is
    // exactly the interesting part), so they're shown as a single moment.
    function mergeSameRace(milestones){
        const out = [];
        for(const m of milestones){
            const prev = out[out.length - 1];
            if(prev && prev.date === m.date && prev.gp === m.gp){
                prev.labels.push(m.label);
                if(m.streakLength != null) prev.streakLength = m.streakLength;
            } else {
                out.push({ ...m, labels: [m.label] });
            }
        }
        return out;
    }

    const STREAK_LABEL = 'Longest winning streak';
    const isTitleLabel = l => /World Title$/.test(l);
    const isWinLabel = l => l === 'First win' || /win with the team$/.test(l);

    // When several milestones land on the same race they're listed in the order they
    // happen within a weekend: debut → pole → points → podium → win
    // → 1st/last with the team → streak → title → best result (last).
    const LABEL_ORDER = [
        'Debut', 'First pole', 'First points', 'First podium', 'First win',
        'First win with the team', 'Last win with the team', STREAK_LABEL,
    ];
    const labelRank = l => {
        const i = LABEL_ORDER.indexOf(l);
        if(i !== -1) return i;
        if(isTitleLabel(l)) return 50;
        return 99;   // "Best result in the team" and anything else: at the end
    };

    const joinLabels = labels => [...labels]
        .sort((a, b) => labelRank(a) - labelRank(b))
        .map((l, i) => i === 0 ? l : l.charAt(0).toLowerCase() + l.slice(1))
        .join(' & ');

    // ── Career strip: one cell per year, from debut to the last season ──
    // A full season with one team is a solid cell in its color; a year without
    // races stays as a hatched gap. A season with more than one team, or one
    // where the driver missed races, is split race by race (career.seasonRaces,
    // from build-careers.js): each slot in the color of the team they raced
    // for, grey where they didn't race. Titles get a gold mark.
    // Hovering shows the season summary in a card with an arrow (ribbonTip
    // below); on a split year, with the team of the hovered race.
    const raced = slot => typeof slot === 'number';

    function racesHtml(slots, eras){
        return slots.map((era, i) => raced(era)
            ? `<b style="--c:${eras[era]?.color || 'var(--primary-red)'}" data-slot="${i}"></b>`
            : `<b class="is-out" data-slot="${i}"></b>`
        ).join('');
    }

    function ribbonHtml(career){
        const seasons = career.seasons;
        const from = seasons[0], to = seasons[seasons.length - 1];
        const titles = career.titleYears || [];
        const split = career.seasonRaces || {};
        const cells = [];

        for(let y = from; y <= to; y++){
            const slots = split[y];
            const era = [...career.eras].reverse().find(e => e.seasons.includes(y)) || null;
            // The year is labeled if a stint with a team starts in it, at the
            // beginning of the season or midway (Lawson 2025: Red Bull Racing).
            const starts = career.eras.some(e => e.from === y);

            cells.push(`
                <li class="jr-year${era ? '' : ' is-gap'}${titles.includes(y) ? ' is-title' : ''}${starts ? ' is-start' : ''}"
                    style="--c:${era?.color || 'transparent'}" data-year="${y}">
                    ${slots ? `<i class="is-split">${racesHtml(slots, career.eras)}</i>` : '<i></i>'}<span>${y}</span>
                </li>
            `);
        }

        return `
            <div class="jr-ribbon">
                <div class="jr-ribbon-head">
                    <p class="jr-ribbon-summary">
                        <b>${plural(career.races, 'race')}</b> across <b>${plural(seasons.length, 'season')}</b>
                        with <b>${plural(career.eras.length, 'team')}</b>
                    </p>
                    ${titles.length ? `<p class="jr-ribbon-legend"><i></i>World title</p>` : ''}
                </div>
                <ol class="jr-years">${cells.join('')}</ol>
            </div>
        `;
    }

    // ── Figures for each team ──
    // Below the ones that are ratios goes the percentage over that stint's
    // races (5 podiums in 37 races and 5 in 120 aren't the same thing); Points
    // gets the per-race average.
    function eraStats(era){
        const races = era.races || 0;
        const pct = n => races ? `${Math.round((n / races) * 100)}%` : '—';

        const items = [
            { label: 'Races',   value: races },
            { label: 'Wins',    value: era.wins,    sub: pct(era.wins) },
            { label: 'Podiums', value: era.podiums, sub: pct(era.podiums) },
            { label: 'Poles',   value: era.poles,   sub: pct(era.poles) },
            { label: 'Points',  value: era.points,  sub: races ? `${(era.points / races).toFixed(1)} / race` : null },
        ];
        // era.best is the best race finish with that team (not the best
        // championship). Only if they didn't win: with wins, "P1" would repeat Wins.
        if(era.best != null && !era.wins){
            items.push({ label: 'Best finish', value: `P${era.best}` });
        }

        return `
            <dl class="jr-stats">
                ${items.map(({ label, value, sub }) => `
                    <div>
                        <dd>${typeof value === 'number' ? fmtNum(value) : value}</dd>
                        <dt>${label}${sub ? ` <span>${sub}</span>` : ''}</dt>
                    </div>
                `).join('')}
            </dl>
        `;
    }

    // ── Milestones as cards ──
    // On top what happened and a badge with the result; below the GP and the date.
    function momentHtml(m){
        const flag = flagUrl(m.iso);
        const isTitle = m.labels.some(isTitleLabel);
        const isStreak = m.labels.includes(STREAK_LABEL);
        const isWin = isTitle || isStreak || m.labels.some(isWinLabel);
        const chip = isTitle
            ? 'WDC'
            : isStreak
                ? `×${m.streakLength}`
                : m.labels.length === 1 && m.labels[0] === 'First pole'
                    ? 'Pole'
                    : `P${m.pos}`;

        return `
            <li class="jr-moment" data-kind="${isTitle ? 'title' : isWin ? 'win' : 'normal'}">
                <div class="jr-moment-top">
                    <p class="jr-moment-label">${joinLabels(m.labels)}</p>
                    <span class="jr-moment-chip">${chip}</span>
                </div>
                <p class="jr-moment-gp">${flag ? `<img class="jr-moment-flag" src="${flag}" alt="" loading="lazy">` : ''}${m.gp} GP</p>
                <p class="jr-moment-date">${prettyDate(m.date)}${isStreak ? ` · ${m.streakLength} wins in a row` : ''}</p>
            </li>
        `;
    }

    // ── All-time records ──
    // They go in the same grid as the other milestones but on their own card (they don't
    // merge with those from the same race: "first win & broke all-time record…"
    // would be unreadable). Below, what happened to that record afterwards.
    const RECORD_NAMES = {
        titles:      ['Most World Championships', 'title', 'titles'],
        wins:        ['Most wins', 'win', 'wins'],
        podiums:     ['Most podiums', 'podium', 'podiums'],
        poles:       ['Most pole positions', 'pole', 'poles'],
        points:      ['Most points', 'point', 'points'],
        fastestLaps: ['Most fastest laps', 'fastest lap', 'fastest laps'],
        starts:      ['Most race starts', 'start', 'starts'],
    };

    function recordHtml(m, nameOf){
        const { key, kind, value, peak, current, after } = m.record;
        const [title, one, many] = RECORD_NAMES[key] || [key, '', ''];
        const flag = flagUrl(m.iso);
        const count = n => `${fmtNum(n)} ${n === 1 ? one : many}`;

        const notes = [];
        if(peak != null && !current) notes.push(`Extended it to ${count(peak)}`);
        if(after){
            notes.push(`${after.type === 'surpassed' ? 'Surpassed' : 'Equalled'} by ${nameOf(after.by)}
                &middot; ${after.gp} GP ${after.year}`);
        }
        if(current) notes.push(`Current record: ${count(peak ?? value)}`);

        return `
            <li class="jr-moment" data-kind="record" data-record="${kind}">
                <div class="jr-moment-top">
                    <p class="jr-moment-label">${kind === 'broke' ? 'Broke all-time record' : 'Equalled all-time record'}</p>
                </div>
                <p class="jr-moment-record">${title} <span>(${fmtNum(value)})</span></p>
                <p class="jr-moment-gp">${flag ? `<img class="jr-moment-flag" src="${flag}" alt="" loading="lazy">` : ''}${m.gp} GP</p>
                <p class="jr-moment-date">${prettyDate(m.date)}</p>
                ${notes.map(n => `<p class="jr-moment-note">${n}</p>`).join('')}
            </li>
        `;
    }

    // ── Strip tooltip ──
    // One card for the whole strip that follows the pointer from slot to slot,
    // with an arrow pointing at the hovered race (or year).

    // Team name with its logo in front (the same one as its chapter below).
    // Not every team has one, older ones especially: ribbonTip() removes the
    // image when it fails, and a dot in the team color takes its place.
    const tipTeamHtml = era => `
        <span class="jr-tip-team" style="--c:${era.color || 'var(--primary-red)'}">${era.teamId
            ? `<img class="jr-tip-logo" src="../img/teams/${era.teamId}-logo.png" alt="">`
            : ''}${era.team}</span>`;

    // The season in one card: year, team, championship position, and points
    // and races. On a split year every team they raced for that season goes
    // one below the other, in order, and the races read as raced / run
    // ("8/17 races"); hovering a grey slot says "Didn't race" (or "Not run
    // yet") in place of the teams.
    function yearTipHtml(year, career, slot = null){
        const slots = career.seasonRaces?.[year] || null;
        const hovered = slot != null ? slots?.[slot] : undefined;
        const era = [...career.eras].reverse().find(e => e.seasons.includes(year));
        if(!era) return `<p class="jr-tip-kicker">${year}</p><p class="jr-tip-title">No races</p>`;
        const teams = slots
            ? [...new Set(slots.filter(raced))].map(i => career.eras[i])
            : [era];
        const title = hovered !== undefined && !raced(hovered)
            ? `<p class="jr-tip-title"><span class="jr-tip-out">${hovered === 'TBD' ? 'Not run yet' : "Didn't race"}</span></p>`
            : teams.map(t => `<p class="jr-tip-title">${tipTeamHtml(t)}</p>`).join('');
        const st = career.seasonStats?.[year];
        const champion = (career.titleYears || []).includes(year);
        const races = slots
            ? `${slots.filter(raced).length}/${slots.filter(s => s !== 'TBD').length} races`
            : st ? plural(st.races, 'race') : null;
        // Two lines: where they finished the championship, then the numbers.
        const standing = champion ? 'World Champion' : st?.pos ? `P${st.pos} in the championship` : null;
        const numbers = st ? `${fmtNum(st.pts)} pts · ${races}` : null;
        return `
            <p class="jr-tip-kicker">${year}</p>
            ${title}
            ${standing ? `<p class="jr-tip-facts${champion ? ' is-champion' : ''}">${standing}</p>` : ''}
            ${numbers ? `<p class="jr-tip-facts">${numbers}</p>` : ''}
        `;
    }

    function ribbonTip(ribbon, career){
        const years = ribbon.querySelector('.jr-years');
        if(!years) return;
        const tip = document.createElement('div');
        tip.className = 'jr-tip';
        tip.setAttribute('role', 'tooltip');
        ribbon.appendChild(tip);
        let current = null;

        function show(target){
            if(target === current) return;
            current = target;
            const year = Number(target.closest('.jr-year').dataset.year);
            tip.innerHTML = yearTipHtml(year, career, target.dataset.slot != null ? Number(target.dataset.slot) : null);

            // The logos arrive after the card is placed and change its size
            // (or are removed if the team has none): placed again when they do.
            const replace = () => { if(current === target) place(target); };
            for(const logo of tip.querySelectorAll('.jr-tip-logo')){
                if(!logo.complete){
                    logo.addEventListener('load', replace, { once: true });
                    logo.addEventListener('error', () => { logo.remove(); replace(); }, { once: true });
                } else if(!logo.naturalWidth){
                    logo.remove();
                }
            }
            place(target);
        }

        function place(target){
            // Above the slot, centered on it without leaving the strip; the
            // arrow keeps pointing at the slot when the card hits an edge.
            const box = ribbon.getBoundingClientRect();
            const r = (target.matches('.jr-year') ? target.querySelector('i') : target).getBoundingClientRect();
            const cx = r.left + r.width / 2 - box.left;
            const w = tip.offsetWidth, h = tip.offsetHeight;
            const left = Math.min(Math.max(cx - w / 2, 0), box.width - w);
            const top = r.top - box.top - h - 12;
            tip.style.setProperty('--arrow-x', `${cx - left}px`);

            // Hidden: it appears in place. Visible: it slides to the new slot.
            if(!tip.classList.contains('is-visible')){
                tip.style.transition = 'none';
                tip.style.transform = `translate(${left}px, ${top}px)`;
                void tip.offsetWidth;
                tip.style.transition = '';
            } else {
                tip.style.transform = `translate(${left}px, ${top}px)`;
            }
            tip.classList.add('is-visible');
        }

        function hide(){
            current = null;
            tip.classList.remove('is-visible');
        }

        years.addEventListener('pointerover', e => {
            const target = e.target.closest('.jr-year i.is-split b') || e.target.closest('.jr-year');
            if(target) show(target);
        });
        years.addEventListener('pointerleave', hide);
    }

    function render(career, nameOf){
        // Each milestone goes in the stint where it happened, in chronological order (the
        // titles arrive at the end of the array but may come before the streak).
        // Records are interleaved by date; in the same race, after the
        // normal milestone.
        const byDate = (a, b) => (a.date || '').localeCompare(b.date || '');
        const eras = career.eras.map(era => {
            const inEra = career.milestones
                .filter(m => era.seasons.includes(m.year) && m.team === era.team)
                .sort(byDate);
            const moments = [
                ...mergeSameRace(inEra.filter(m => !m.record)).map(m => ({ m, html: momentHtml(m) })),
                ...inEra.filter(m => m.record).map(m => ({ m, html: recordHtml(m, nameOf), isRecord: true })),
            ].sort((a, b) => byDate(a.m, b.m) || (a.isRecord ? 1 : 0) - (b.isRecord ? 1 : 0));
            return { ...era, moments };
        });

        root.innerHTML = `
            ${ribbonHtml(career)}

            <ol class="jr-eras">
                ${eras.map((era, i) => `
                    <li class="jr-era" style="--c:${era.color || 'var(--primary-red)'}">
                        <div class="jr-era-id">
                            <span class="jr-era-index">${pad2(i + 1)}</span>
                            ${era.teamId ? `<img class="jr-era-logo" src="../img/teams/${era.teamId}-logo.png" alt="" onerror="this.remove()">` : ''}
                            <h3 class="jr-era-team">${era.team}</h3>
                            <p class="jr-era-years">${seasonLabel(era.seasons)} · ${plural(era.seasons.length, 'season')}</p>
                            ${era.titles?.length ? `<p class="jr-era-titles">${era.titles.length}× World Champion</p>` : ''}
                        </div>
                        <div class="jr-era-main">
                            ${eraStats(era)}
                            ${era.moments.length ? `<ul class="jr-moments">${era.moments.map(x => x.html).join('')}</ul>` : ''}
                        </div>
                    </li>
                `).join('')}
            </ol>
        `;
    }

    (async function init(){
        let careers, drivers;
        try {
            ({ careers, drivers } = await window.driverData);
        } catch (err) {
            console.error('Could not load careers.json', err);
            root.classList.add('is-empty');
            return;
        }

        const career = careers[driverId];
        if(!career || !career.eras?.length){ root.classList.add('is-empty'); return; }
        // Name of whoever beat or equalled a record, from drivers.json.
        const nameOf = id => {
            const d = drivers?.[id];
            return d ? `${d.firstName} ${d.lastName}` : id.replace(/-/g, ' ');
        };
        render(career, nameOf);
        const ribbon = root.querySelector('.jr-ribbon');
        if(ribbon) ribbonTip(ribbon, career);
    })();
})();
